version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${NODE_APP_PORT}:3000"
      - "5555:5555"
    depends_on:
      - db
    networks:
      - app_network
    env_file:
      - .env

  db:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  pg_data:
